tasks:
  - name: download and create container
    init: |
      gp open README.md

      # pull and start container:
      docker pull container-registry.oracle.com/database/adb-free:latest-23ai
      docker run -d \
        -p 1521:1522 \
        -p 1522:1522 \
        -p 8443:8443 \
        -p 27017:27017 \
        -e WORKLOAD_TYPE=ATP \
        -e WALLET_PASSWORD='Welkom01#123' \
        -e ADMIN_PASSWORD='Welkom01#123' \
        --cap-add SYS_ADMIN \
        --device /dev/fuse \
        --name adb-free \
        container-registry.oracle.com/database/adb-free:latest-23ai
      
      gp sync-done create-container

      # fetch SQLcl
      wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
      unzip sqlcl-latest.zip -d /workspace/
      rm -f sqlcl-latest.zip

      wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-7.0.asc
      wget https://downloads.mongodb.com/compass/mongodb-mongosh_2.2.6_amd64.deb
      sudo dpkg -i mongodb-mongosh_2.2.6_amd64.deb
      rm -f mongodb-mongosh_2.2.6_amd64.deb

      echo "Waiting for database to settle..."
      sleep 120

      # copy cloud wallet and create a zip file for it.
      docker cp adb-free:/u01/app/oracle/wallets/tls_wallet adb_wallet
      pushd adb_wallet && zip ../adb.zip * && popd

      # Use previously created cloud wallet to connect and run the create schema script
      /workspace/sqlcl/bin/sql -cloudconfig adb.zip admin/Welkom01#123@myatp_tp @ scripts/create_schema.sql

      gp sync-done database-running

  - name: start container
    init: gp sync-await database-running
    command: |
      docker start adb-free

  - name: Show log
    init: gp sync-await create-container
    command: docker logs -f adb-free

ports:
  - port: 1521
    onOpen: ignore
    visibility: private
  - port: 1522
    onOpen: ignore
    visibility: private
  - port: 8443
    onOpen: ignore
    visibility: private
    protocol: https
  - port: 27017
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - ms-dotnettools.vscode-dotnet-runtime
    - oracle.oracledevtools
    - mongodb.mongodb-vscode
