tasks:
  - name: download and create container
    before: |
      docker pull container-registry.oracle.com/database/adb-free:latest-23ai
      docker run -d \
        -p 1521:1522 \
        -p 1522:1522 \
        -p 8443:8443 \
        -p 27017:27017 \
        -e WORKLOAD_TYPE=ATP \
        -e WALLET_PASSWORD='Welkom01#123' \
        -e ADMIN_PASSWORD='Welkom01#123' \
        --cap-add SYS_ADMIN \
        --device /dev/fuse \
        --name adb-free \
        container-registry.oracle.com/database/adb-free:latest-23ai

      curl --output sqlcl-latest.zip https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
      unzip sqlcl-latest.zip -d /workspace/
      rm -f sqlcl-latest.zip

      sleep 60
      
      docker cp adb-free:/u01/app/oracle/wallets/tls_wallet adb_wallet
      pushd adb_wallet && zip ../adb.zip * && popd

      gp sync-done database-running
    init:
      gp open README.md

  - name: start container and run a session as  owner
    init: gp sync-await database-running
    command: |
      docker start adb-free 

  - name: Show log
    command: docker logs -f adb-free

ports:
  - port: 1521
    onOpen: notify
    visibility: private
  - port: 1522
    onOpen: ignore
    visibility: private
  - port: 8443
    onOpen: notify
    visibility: private
    protocol: https
  - port: 27017
    onOpen: notify
    visibility: private

vscode:
  extensions:
    - ms-dotnettools.vscode-dotnet-runtime
    - oracle.oracledevtools
    - mongodb.mongodb-vscode
